### ISSUE TITLE
Error-Log

### ISSUE THREAD

**Issue by trombose009** [gbeine/fronius2mqtt#1]
Hi, 

thanks a lot for this project. I wanna run it in docker an get this error log:

```
`DEBUG:root:Starting MQTT
Traceback (most recent call last):
  File "/fronius2mqtt/./fronius2mqtt", line 333, in <module>
    main()
    ~~~~^^
  File "/fronius2mqtt/./fronius2mqtt", line 326, in main
    mqtt_client = init_mqtt()
  File "/fronius2mqtt/./fronius2mqtt", line 205, in init_mqtt
    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
           ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
                 ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4612, in _create_socket
    sock = self._ssl_wrap_socket(sock)
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4671, in _ssl_wrap_socket
    ssl_sock.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function _DeleteDummyThreadOnDel.__del__ at 0xb679f078>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1383, in __del__
TypeError: 'NoneType' object does not support the context manager protocol`
```

config file:
```

{
    "mqtt_host": "192.168.178.44",
    "mqtt_port": "1883",
    "mqtt_clientid": "fronius2mqtt",
    "mqtt_topic": "fronius",
    "mqtt_tls": "false",
    "mqtt_tls_version": "TLSv1.2",
    "mqtt_verify_mode": "CERT_NONE",
    "mqtt_tls_no_verify": "false",
    "http_host": "192.168.178.121",
    "http_port": 80,
    "mqtt_keepalive": "300",
    "verbose": "false"
}


```

**Comment by gbeine** [comment]
It seems, you're missing the credentials for MQTT.

If `mqtt_tls` is `false`, you should leave out `mqtt_tls_version`, `mqtt_verify_mode`, `mqtt_tls_no_verify` - they will have no effect.
I'm not quite sure why there is a reference to `_ssl_wrap_socket` in the output.

But what you might need are `mqtt_user` and `mqtt_password`.

You can also try to set `verbose` to `true` to get some more information.

**Comment by trombose009** [comment]
thanks for answering. I modyfied the conf file as u said but there is still an error.

```
DEBUG:root:Starting MQTT
Traceback (most recent call last):
  File "/fronius2mqtt/./fronius2mqtt", line 333, in <module>
    main()
    ~~~~^^
  File "/fronius2mqtt/./fronius2mqtt", line 326, in main
    mqtt_client = init_mqtt()
  File "/fronius2mqtt/./fronius2mqtt", line 205, in init_mqtt
    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
           ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
                 ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4612, in _create_socket
    sock = self._ssl_wrap_socket(sock)
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4671, in _ssl_wrap_socket
    ssl_sock.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function _DeleteDummyThreadOnDel.__del__ at 0xb670a078>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1383, in __del__
TypeError: 'NoneType' object does not support the context manager protocol
```

**Comment by gbeine** [comment]
For some reason, your MQTT client is trying to connect via SSL which is not configured.
Are there any SSL/TLS related config options in your config file?
If yes, try to remove them.

If that does not solve the issue, please have a look on your docker network configuration.

**Comment by gbeine** [comment]
Good news - I've located the problem an can fix it this weekend.

**Comment by gbeine** [comment]
@trombose009 I've fixed the problem with config parsing.
A new version of the docker image is available.

**Comment by trombose009** [comment]
ok, I have tried it now but I still get an error. here is my conf file:

```
{
    "mqtt_host": "localhost",
    "mqtt_port": "1883",
    "mqtt_clientid": "fronius2mqtt",
    "mqtt_topic": "fronius",
    "mqtt_tls": "false",
    "http_host": "192.168.178.121",
    "http_port": 80,
    "mqtt_keepalive": "30",
    "verbose": "false"
}
```
and here the error message:

```
Traceback (most recent call last):

  File "/fronius2mqtt/./fronius2mqtt", line 346, in <module>

    main()

    ~~~~^^

  File "/fronius2mqtt/./fronius2mqtt", line 338, in main

    mqtt_client = init_mqtt()

  File "/fronius2mqtt/./fronius2mqtt", line 200, in init_mqtt

    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)

    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435, in connect

    return self.reconnect()

           ~~~~~~~~~~~~~~^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598, in reconnect

    self._sock = self._create_socket()

                 ~~~~~~~~~~~~~~~~~~~^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4609, in _create_socket

    sock = self._create_socket_connection()

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection

    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)

           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection

    raise exceptions[0]

  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection

    sock.connect(sa)

    ~~~~~~~~~~~~^^^^

OSError: [Errno 99] Address not available


```
maybe I do something wrong

**Comment by gbeine** [comment]
> `OSError: [Errno 99] Address not available`

Yes, this is the normal error when you try to use "localhost" from a docker container.
You need to specify the IP address of your MQTT server as `"mqtt_host": "localhost"`

**Comment by trombose009** [comment]
```
Traceback (most recent call last):

  File "/fronius2mqtt/./fronius2mqtt", line 346, in <module>

    main()

    ~~~~^^

  File "/fronius2mqtt/./fronius2mqtt", line 338, in main

    mqtt_client = init_mqtt()

  File "/fronius2mqtt/./fronius2mqtt", line 200, in init_mqtt

    mqtt_client.connect(daemon_args.mqtt_host, daemon_args.mqtt_port, daemon_args.mqtt_keepalive)

    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435, in connect

    return self.reconnect()

           ~~~~~~~~~~~~~~^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598, in reconnect

    self._sock = self._create_socket()

                 ~~~~~~~~~~~~~~~~~~~^^

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4609, in _create_socket

    sock = self._create_socket_connection()

  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection

    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)

           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.13/socket.py", line 864, in create_connection

    raise exceptions[0]

  File "/usr/local/lib/python3.13/socket.py", line 849, in create_connection

    sock.connect(sa)

    ~~~~~~~~~~~~^^^^

OSError: [Errno 99] Address not available


```

**Comment by trombose009** [comment]
irgendwie läuft's immer noch nicht :/

**Comment by trombose009** [comment]
also ich habe zwischenzeitlich auch ne andere lösung. aber ich kann das gerne noch mit troubleshooten. es sei denn es liegt einfach an mir

**Comment by gbeine** [comment]
Address not available heißt, dass du aus dem Docker-Container heraus den Host nicht erreichen kannst, den du als MQTT-Host konfigurierst.
Das ist ein Problem deines Docker-Setups, das kenne ich nicht und dafür kann ich auch keinen Support leisten.
